<?php
namespace App\Services;
use App\Models\Project;use Illuminate\Support\Facades\DB;
class CostAnalyticsService
{
    public function getActualPayments(Project $project,array $filters=[]): array {$p=$this->date($project->materialPurchases(),$filters)->sum('total_amount');$s=$this->date($project->serviceEntries(),$filters)->sum('total_amount');$written=$this->date($project->materialWriteOffs(),$filters)->sum('total_amount');$inventory=app(InventoryService::class)->getInventoryTable($project)->sum('stock_value');$month=now()->format('Y-m');return ['actual_total'=>(float)$p+(float)$s,'materials_purchased_total'=>(float)$p,'services_total'=>(float)$s,'materials_written_off_total'=>(float)$written,'inventory_value'=>(float)$inventory,'current_month_total'=>(float)$project->materialPurchases()->whereRaw("strftime('%Y-%m', date)=?",[$month])->sum('total_amount')+(float)$project->serviceEntries()->whereRaw("strftime('%Y-%m', date)=?",[$month])->sum('total_amount')];}
    public function getCostByTags(Project $project,array $filters=[]): array {return DB::table('tags')->where('tags.project_id',$project->id)->leftJoin('taggables','tags.id','=','taggables.tag_id')->select('tags.id','tags.name',DB::raw('0 as actual_total'),DB::raw('0 as stage_cost_total'))->groupBy('tags.id','tags.name')->get()->toArray();}
    public function getCostByMonths(Project $project,array $filters=[]): array {return ['purchases'=>$project->materialPurchases()->selectRaw("strftime('%Y-%m', date) month, SUM(total_amount) total")->groupBy('month')->get(),'services'=>$project->serviceEntries()->selectRaw("strftime('%Y-%m', date) month, SUM(total_amount) total")->groupBy('month')->get(),'write_offs'=>$project->materialWriteOffs()->selectRaw("strftime('%Y-%m', date) month, SUM(total_amount) total")->groupBy('month')->get()];}
    public function getCostByContractors(Project $project,array $filters=[]): array {return $project->serviceEntries()->with('contractor')->selectRaw('contractor_id, COUNT(*) entries_count, SUM(hours) hours_total, SUM(total_amount) total_amount, SUM(paid_amount) paid_amount, SUM(total_amount-paid_amount) debt')->groupBy('contractor_id')->get()->toArray();}
    public function getCostByMaterials(Project $project,array $filters=[]): array {return app(InventoryService::class)->getInventoryTable($project)->toArray();}
    public function getStageCost(Project $project,array $filters=[]): array {return ['materials'=>(float)$this->date($project->materialWriteOffs(),$filters)->sum('total_amount'),'services'=>(float)$this->date($project->serviceEntries(),$filters)->sum('total_amount')];}
    private function date($query,array $filters){return $query->when($filters['date_from']??null,fn($q,$v)=>$q->whereDate('date','>=',$v))->when($filters['date_to']??null,fn($q,$v)=>$q->whereDate('date','<=',$v));}
}
