<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('projects',function(Blueprint $table){$table->id();$table->foreignId('user_id')->constrained()->cascadeOnDelete();$table->string('name');$table->string('address')->nullable();$table->text('description')->nullable();$table->string('status')->default('active')->index();$table->date('started_at')->nullable();$table->date('finished_at')->nullable();$table->timestamps();});
Schema::create('units',function(Blueprint $table){$table->id();$table->string('name');$table->string('short_name')->unique();$table->timestamps();});
Schema::create('materials',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->foreignId('unit_id')->constrained()->restrictOnDelete();$table->string('name');$table->string('sku')->nullable();$table->text('description')->nullable();$table->boolean('is_active')->default(true);$table->timestamps();$table->unique(['project_id','name']);});
Schema::create('contractors',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->string('name');$table->string('phone')->nullable();$table->string('email')->nullable();$table->text('comment')->nullable();$table->boolean('is_active')->default(true);$table->timestamps();});
Schema::create('tags',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->string('name');$table->string('slug');$table->string('color')->nullable();$table->timestamps();$table->unique(['project_id','slug']);});
Schema::create('material_purchases',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->date('date')->index();$table->string('supplier_name')->nullable();$table->string('document_number')->nullable();$table->string('payment_status')->default('paid')->index();$table->decimal('total_amount',14,2)->default(0);$table->text('comment')->nullable();$table->timestamps();});
Schema::create('material_purchase_items',function(Blueprint $table){$table->id();$table->foreignId('material_purchase_id')->constrained()->cascadeOnDelete();$table->foreignId('material_id')->constrained()->restrictOnDelete();$table->decimal('quantity',14,3);$table->decimal('unit_price',14,2);$table->decimal('total_price',14,2);$table->timestamps();});
Schema::create('material_write_offs',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->foreignId('material_id')->constrained()->restrictOnDelete();$table->date('date')->index();$table->decimal('quantity',14,3);$table->decimal('unit_price',14,2);$table->decimal('total_amount',14,2);$table->text('comment')->nullable();$table->timestamps();});
Schema::create('inventory_movements',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->foreignId('material_id')->constrained()->restrictOnDelete();$table->date('date')->index();$table->string('type')->index();$table->decimal('quantity',14,3);$table->decimal('unit_price',14,2)->nullable();$table->decimal('amount',14,2)->nullable();$table->nullableMorphs('source');$table->text('comment')->nullable();$table->timestamps();});
Schema::create('service_entries',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->foreignId('contractor_id')->nullable()->constrained()->nullOnDelete();$table->date('date')->index();$table->string('name');$table->string('pricing_type')->index();$table->decimal('hours',10,2)->nullable();$table->decimal('quantity',14,3)->nullable();$table->string('unit_name')->nullable();$table->decimal('unit_price',14,2)->nullable();$table->decimal('hourly_rate',14,2)->nullable();$table->decimal('total_amount',14,2);$table->string('payment_status')->default('paid')->index();$table->decimal('paid_amount',14,2)->default(0);$table->text('comment')->nullable();$table->timestamps();});
Schema::create('taggables',function(Blueprint $table){$table->id();$table->foreignId('tag_id')->constrained()->cascadeOnDelete();$table->morphs('taggable');$table->timestamps();$table->unique(['tag_id','taggable_type','taggable_id'],'taggables_unique');});
Schema::create('attachments',function(Blueprint $table){$table->id();$table->foreignId('project_id')->constrained()->cascadeOnDelete();$table->morphs('attachable');$table->string('file_path');$table->string('original_name');$table->string('mime_type');$table->unsignedBigInteger('size');$table->timestamps();});
} public function down():void{foreach(['attachments','taggables','service_entries','inventory_movements','material_write_offs','material_purchase_items','material_purchases','tags','contractors','materials','units','projects'] as $table){Schema::dropIfExists($table);}}};
